project:
  type: website

website:
  title: "Rachel Kruger"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Home"
      - href: publications.qmd
        text: "Publications"
      - href: CV.qmd
        text: "CV"
      - href: photos.qmd
        text: "Photos"
        
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

